language: node_js

node_js:
    - "7"

before_script:
    - npm install --dev
    - npm install coveralls

script:
    - npm test
    - npm run coverage
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
